### ISSUE TITLE
Set correct appVersion

### ISSUE THREAD

**Issue by mattfarina** [gkarthiks/helm-charts#1]
In the `Chart.yaml` file the `appVersion` is set to `"1.0"`. It may be a good idea to use the real version of the application as it shows up in the hub. The versions are at https://github.com/danielqsj/kafka_exporter/releases.

**Comment by gkarthiks** [comment]
@mattfarina  got it. I will re-built and push to my repo. Thanks for suggestions :) .

**Comment by gkarthiks** [comment]
@mattfarina  fixed and pushed the changes 
![image](https://user-images.githubusercontent.com/30545166/58930334-aee4cc00-870f-11e9-95cf-7c9b5a46d943.png)

closing this, please re-open if you feel something needs to changed.
