### ISSUE TITLE
[prometheus-kafka-exporter] PodSecurityPolicy with extensions/v1beta1

### ISSUE THREAD

**Issue by hazim1093** [gkarthiks/helm-charts#5]
Hi, 

Chart deployments fails in newer kubernetes versions due to PodSecurityPolicy having apiVersion `extensions/v1beta1`. 
I see that it was updated last month but still there are 2 PodSecurityPolicy resources generated on with the old apiVersion and one with the new. 

Even when setting `rbac.pspEnabled` to false, the PodSecurityPolicy with old apiVersion is still created. 

Not sure where that comes from

**Comment by hazim1093** [comment]
The chart also has 2 deployments and 2 of each resource. Seems like the old and new chart has been merged somehow

**Comment by gkarthiks** [comment]
Aah.. thanks for raising this issue @hazim1093 . I will get this fixed in this weekend.

**Comment by gkarthiks** [comment]
@hazim1093  this is fixed now. Closing this issue.
